### ISSUE TITLE
Repo recipe visible but not working

### ISSUE THREAD

**Issue by screig** [sonatype/nexus-repository-r#8]
I can see the R repo recipe, but cannot click-on/select it.

![image](https://user-images.githubusercontent.com/4292074/29264118-b59f8c2c-80d3-11e7-8e59-87f2d9bcd05e.png)

Also saw this message in the log.

> 2017-08-14 10:28:09,373+0200 WARN  [Karaf local console user karaf] *SYSTEM com.google.inject.spi.InjectionPoint - Method: public void org.sonatype.nexus.repository.r.internal.RRecipeSupport.setBrowseUnsupportedHandler(org.sonatype.nexus.repository.view.handlers.BrowseUnsupportedHandler) is not annotated with @Inject but is overriding a method that is annotated with @javax.inject.Inject.  Because it is not annotated with @Inject, the method will not be injected. To fix this, annotate the method with @Inject.

**Comment by DarthHater** [comment]
What version of Nexus Repo are you using, etc...?

**Comment by DarthHater** [comment]
I feel like we can close this, yeah @screig ? Seems that you've gotten things working.

**Comment by screig** [comment]
Yes. Please do

_Sent from my Google Nexus 7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
