### ISSUE TITLE
Permanent Install instructions do not seem to work

### ISSUE THREAD

**Issue by screig** [sonatype/nexus-repository-r#9]
Followed your instructions for permanent install.

- Built the jar file

- Deployed here

![image](https://user-images.githubusercontent.com/4292074/29264617-b3442db4-80d5-11e7-8b09-3367aba34351.png)

- Added necessary config lines

![image](https://user-images.githubusercontent.com/4292074/29264739-24927a02-80d6-11e7-9da5-f9799660c1f5.png)
and
![image](https://user-images.githubusercontent.com/4292074/29264759-3912b8ca-80d6-11e7-978f-b48ae1ce6736.png)

but it will not load the R plugin on starting.

```
# sudo su - nexus
$ cd <nexus_dir>/bin
$ ./nexus run
bundle:list
```

![image](https://user-images.githubusercontent.com/4292074/29264894-c462ba10-80d6-11e7-9ad1-86c14b8d88d3.png)

Have to manually execute 

![image](https://user-images.githubusercontent.com/4292074/29264960-06f6e93c-80d7-11e7-90a0-49b8ba36ae35.png)

Is it not starting automatically because of the warnings?

Thanks
Sean

**Comment by DarthHater** [comment]
Love the scribbles on your screenshot. I'll take a look at this today.

**Comment by screig** [comment]
IP address

**Comment by screig** [comment]
now i'm really having fun

Sonatype Nexus (3.5.0-02)

![image](https://user-images.githubusercontent.com/4292074/29287068-1ac8171a-812c-11e7-896d-ced3a49d3b88.png)

now as I created an R repo previously, it gets upset that the plugin is not there and shutsdown

![image](https://user-images.githubusercontent.com/4292074/29287117-4944fd74-812c-11e7-9443-0d482c58da15.png)

**Comment by DarthHater** [comment]
Right, this is because OrientDB still has references to the r-hosted recipe, but it's not there on startup (duh, right). I'll be taking a look at this shortly.

**Comment by screig** [comment]
very kind, I am grateful, ps I think this will be excellent. There is nobody doing an R repo now.

**Comment by DarthHater** [comment]
Hi there @screig , gave this a shot tonight and it worked! Here's what I did. From the Nexus Repo directory, I copied the built `nexus-repository-r-1.0.0.jar` into:

`nexus-3.5.1-SNAPSHOT/system/org/sonatype/nexus/plugins/nexus-repository-r/1.0.0`

Then I made changes to:

`nexus-3.5.1-SNAPSHOT/system/com/sonatype/nexus/assemblies/nexus-oss-feature/3.5.1-SNAPSHOT/nexus-oss-feature-3.5.1-SNAPSHOT-features.xml`

Changes I made were:

```
    <feature name="nexus-repository-r" description="org.sonatype.nexus.plugins:nexus-repository-r" version="1.0.0">
        <details>org.sonatype.nexus.plugins:nexus-repository-r</details>
        <bundle>mvn:org.sonatype.nexus.plugins/nexus-repository-r/1.0.0</bundle>
    </feature>
```

And:

```
	<feature version="1.0.0" prerequisite="false" dependency="false">nexus-repository-r</feature>
```

They need to be made in the appropriate sections (which should be obvious, but if it's not let me know!)

From there I ran Nexus Repo and it booted up fine. Mind giving it a shot and letting me know how it goes?

**Comment by screig** [comment]
So this

![image](https://user-images.githubusercontent.com/4292074/29309681-ae439052-81a2-11e7-9ebf-351f04a9e8df.png)

becomes

![image](https://user-images.githubusercontent.com/4292074/29309787-22dfa0d6-81a3-11e7-9c99-813d607f50aa.png)


feature section, no change

![image](https://user-images.githubusercontent.com/4292074/29309760-06caf38c-81a3-11e7-9a5a-f670a415cb55.png)

Still get the same error:

![image](https://user-images.githubusercontent.com/4292074/29309868-65429d66-81a3-11e7-9f76-11d527b3f751.png)

**Comment by mcculls** [comment]
Did you also remove that bundle from the deploy directory?

Is it possible to see the entire startup log? You can create an issue on http://issues.sonatype.org and attach it there (or generate a support zip and attach that).

It would also be useful to see the content of the following files from the `nexus-repository-r` jar:
```
META-INF/MANIFEST.MF
META-INF/sisu/javax.inject.Named
```
just in case the issue lies in the plugin itself.

**Comment by screig** [comment]
> Did you also remove that bundle from the deploy directory?

That was it.

**Comment by DarthHater** [comment]
Awesome, glad you are in business!
